// ----------------------------------------------------------------------------
// $Id$
// ----------------------------------------------------------------------------
// Public Domain C Library - http://pdclib.sourceforge.net
// This code is Public Domain. Use, modify, and redistribute at will.
// ----------------------------------------------------------------------------
// Input/output - personality
// ----------------------------------------------------------------------------

#define BUFSIZ       // buffer size (see setvbuf()), >= 256
#define FOPEN_MAX    // supported number of simultaneously open files, >= 8
#define FILENAME_MAX // supported length of filenames
#define L_tmpnam     // length of filenames generated by tmpnam() including \0
#define TMP_MAX      // number of unique filenames generateable by tmpnam(),
                     // >= 25

#define stderr // FILE *
#define stdin  // FILE *
#define stdout // FILE *

// storing return code in fh->HostRC
void __pdc_fclose( FILE * fh );
